#!/bin/bash

# Copyright (C) 2012 Royal Dutch Army
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

echo "Getting Git SHA into ${1}"
if [[ ! -d "$(dirname "${1}")" ]]; then
  mkdir -p "$(dirname "${1}")"
fi
cat > "${1}" << EOF
git.sha = $(git rev-list -1 HEAD)
git.descriptor = $(git describe --dirty --always)
EOF