#!/bin/bash

echo "Getting Git SHA into ${1}"
if [[ ! -d "$(dirname "${1}")" ]]; then
  mkdir -p "$(dirname "${1}")"
fi
cat > "${1}" << EOF
git.sha = $(git rev-list -1 HEAD)
git.descriptor = $(git describe --dirty --always)
EOF