#!/bin/bash

echo "Getting Git SHA into ${1}"
if [[ ! -d "$(dirname "${1}")" ]]; then
  mkdir "$(dirname "${1}")"
fi
gitsha="$(git describe --always)"
echo "git.sha = ${gitsha}"
echo "git.sha = ${gitsha}" > "${1}"
